# Generated by Django 5.2.13 on 2026-04-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
