# Generated by Django 5.2.13 on 2026-04-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_damagereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
